secretrobotron/games

pong/components.js, pong/controls.js, pong/convert.js, pong/index.html, pong/test.css, pong/test.js
Hey @secretrobotron - check out ``controls.js`` to see how the gamepad API stuff works.
It's weird but you have to query for the gamepads every frame.
In case you have a gamepad, check out this page to see how the buttons work etc...
http://beej.us/blog/data/javascript-gamepad/
=> Gamepad Support + Collision Detection

battle-pong/controls.js, pong/index.html
* Removed reference to ``controls.js`` from ``/pong/index.html`` since it 404s trying to get it
* Mapped ``D`` on the keyboard to have the same effect as the ``A`` key
* This way if you don't like the way ``A`` and ``D`` rotate the paddle, you can just use ``D`` and ``S`` to get a different feeling mapping.
=> Some updates

battle-pong/game.js, battle-pong/paddle.js, battle-pong/style.css
=> Added scared shaking to the Finish screen.

battle-pong/game.js, battle-pong/index.html, battle-pong/style.css, battle-pong/todo.md, pong/paddle.js
If you hold the ball in your side for longer than 5 seconds and the ball is going very slowly you start losing terrain.
=> Ball hold penalty thing

battle-pong/src/js/paddle.js
1. Added staged paddle movement routing system.
2. Implemented "slapshot" for paddles using right analog stick
3. Misc cleanup to make things easier to read and cleaner to function.
=> Slapshot (and paddle cleanup)

battle-pong/src/js/effects.js, battle-pong/src/js/settings.js, battle-pong/src/js/sounds.js
@flukeout @DevonBird I just had to check this out, and it works pretty well.
After the bomb explodes, I apply a lowpass filter to all sound effects (which could be changed so that only select sounds go through the filter). It fades away over time.
=> Lowpass filter effect which kicks in after bomb

battle-pong/splash.html, battle-pong/src/js/splash.js
Fixes a bug where splash page didn't have access to audio
=> Added sounds to splash

battle-pong/src/js/ball.js, battle-pong/src/js/debug.js, battle-pong/src/js/game.js, battle-pong/src/js/sounds.js
... to ball so that it can manage spinning sound properly for spin powerup.
=> Added preventative measures and destroy functions

battle-pong/paddle-test.html, battle-pong/splash.html, battle-pong/src/js/input-mappings.js, battle-pong/src/js/paddle.js, battle-pong/src/js/settings.js, battle-pong/src/js/splash.js, battle-pong/src/scss/splash.scss
1. Added test page for just trying controls.
2. Use right analog stick on gamepads to spin paddle. Both axes.
=> Right analog stick spinning

battle-pong/paddle-test.html, battle-pong/src/js/components.js, battle-pong/src/js/input.js, battle-pong/src/js/paddle.js
Some updates on spinning with analog stick. Paddles spin in opposite direction when using Y axis on right analog stick.
Added a lot to `paddle-test` to debug paddle spinning. Found a few problems as a result, like #126 and #127.
Fixes #127
=> Analog spinning 2

battle-pong/src/js/ball.js
And also improved some logic about adding a classname to the ball when it's got the sticky powerup.
FYI @secretrobotron  — i'll merge
=> Fixed a slowdown after two hard goals bug

battle-pong/splash.html, battle-pong/src/js/ball.js, battle-pong/src/js/paddle.js, battle-pong/src/js/settings.js
Does this now...
https://giphy.com/gifs/5C0Enzn0IBLPe4y5sQ
**How to use it**
* If you have the spin powerup, hit the ball into the wall
* It will start curving / wallbouncing towards the opposite ends
* It stops spin-bouncing if it hits anything along the way
cc @secretrobotron - imma merge.
=> Changed Spin Powerup

battle-pong/src/js/ball.js, battle-pong/src/js/paddle.js
Minor cleanup making sure we don't keep querySelectoring over and over
* There are a bunch of places in the game where we constantly reselect, or add/remove classes every frame needlessly. Gotta comb through it and clean it up.
=> Some cleanup

battle-pong/src/js/paddle.js
=> Fixed no clip timeout not working correctly

battle-pong/rules.html, battle-pong/src/js/input.js, battle-pong/src/js/pause.js, battle-pong/src/js/rules.js
1. Made InputManager.GamepadEventManager to handle simple gamepad button pressing magic.
2. Connected InputManager.GamepadEventManager to rules.js.
3. Added relevant stuff to rules.html.
=> Gamepad functionality in menus

battle-pong/src/js/game.js
Quick bugfix for a scoring thing.
=> Removing scoring indicators when the round is over

battle-pong/src/js/ball.js
Added a dash for now, but might want something more
=> Made the initial Spin hit sound like a dash

battle-pong/src/js/game.js, battle-pong/src/js/start.js
Removes the longer delay between rounds. We can now specify a delay to roundstart if we want, i added it as an argument to that function.
=> Fixes the delay between rounds

battle-pong/src/js/ball.js
The own zone hit was only triggering on the right-side wall. This fixes that.
=> Fixes missing ‘own zone’ hit on left wall.

battle-pong/src/js/sounds.js
Start & stop both check for spinLoop.
Fixes #168
=> Added extra protection for spinning sound sequence

battle-pong/src/js/game.js, battle-pong/src/js/menu-controls.js
Make the music SING!
Also some little bug fixes.
=> Add intensity when round ends.
